name: Exercises

packages:
  - accessibility/**
  - animation/**
  - architecture/**
  - dart/**
  - documentation/**
  - linter/**
  - modularizing/**
  - native/**
  - styling_platforms/**
  - widget/**
