name: person_manager
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: 2.2.0
  uuid: 3.0.7
  flutter_modular: 6.0.1
  result_dart: 1.1.0
  flutter_triple: 2.1.4
  flutter_bloc: 8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: 0.3.0
  bloc_test: 9.1.4
  triple_test: ^2.0.0

flutter:
  uses-material-design: true
